[package]
name = "pointctl"
version = "0.1.0"
authors = ["Gijs van Steenpaal <gijs.van.steenpaal@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities", "science","visualization"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Used for parsing CLI commands
clap = "^2.33.1"
# Used for visualization
kiss3d="0.24.*"
nalgebra = "*"
# Used for generarting random points
rand = "^0.7"
rand_distr = "*"
# Spacial datastructures sued for fast ann search
hnsw = "0.6.1"
space = "0.10.3"
# Used for calling CUDA FFI
rustacuda = "0.1"
rustacuda_core = "0.1"
rustacuda_derive = "0.1"

[profile.release]
debug = true
