[package]
name = "pointcloud-processing"
version = "0.1.0"
authors = ["Gijs van Steenpaal <gijs.van.steenpaal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2.33.1"
nalgebra = "*"
rand = "^0.7"
rand_distr = "*"